# Generated by Django 2.2.2 on 2019-06-12 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_djangoboard'),
        ('boards', '0002_comment'),
    ]

    operations = [
    ]
