# Generated by Django 2.2.2 on 2019-06-26 20:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(error_messages={'unique': '이미 존재하는 아이디입니다.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='아이디')),
                ('user_name', models.CharField(max_length=20, verbose_name='성명')),
                ('profilepic', models.ImageField(upload_to='pic_folder/', verbose_name='프로필 이미지')),
                ('job', models.PositiveSmallIntegerField(blank=True, choices=[(1, '일반인'), (2, '학계'), (3, '정치계'), (4, '산업계')], null=True, verbose_name='영역')),
                ('age', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)], verbose_name='나이')),
                ('gender', models.CharField(choices=[('여성', '여성'), ('남성', '남성')], default='남성', max_length=2, verbose_name='성별')),
                ('text', models.TextField(verbose_name='자기소개')),
                ('date_of_birth', models.DateField(verbose_name='생년월일')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('followers', models.ManyToManyField(related_name='followings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
