# Generated by Django 2.2.2 on 2019-06-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('여성', '여성'), ('남성', '남성')], default='남성', max_length=2, verbose_name='성별'),
        ),
    ]
