# Generated by Django 2.2.2 on 2019-06-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(upload_to='pic_folder/', verbose_name='프로필 이미지'),
        ),
    ]
