# Generated by Django 2.2.2 on 2019-06-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20190624_1403'),
        ('boards', '0002_auto_20190624_1403'),
        ('accounts', '0002_auto_20190624_1359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='User',
        ),
    ]
