# Generated by Django 2.2.2 on 2019-06-24 14:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190624_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)], verbose_name='나이'),
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('F', '여성'), ('M', '남성')], default='M', max_length=1, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '일반인'), (2, '학계'), (3, '정치계'), (4, '산업계')], null=True, verbose_name='영역'),
        ),
        migrations.AddField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/', verbose_name='프로필 이미지'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='성명'),
            preserve_default=False,
        ),
    ]
