# Generated by Django 2.2.2 on 2019-06-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_name', models.CharField(max_length=200)),
                ('law_people', models.CharField(max_length=200)),
                ('law_department', models.CharField(max_length=200)),
                ('law_condition', models.CharField(max_length=200)),
                ('law_date', models.CharField(max_length=200)),
                ('law_doc_num', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LawNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_num_num', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NumData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_num_num', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_num', models.CharField(max_length=200)),
                ('raw_name', models.CharField(max_length=200)),
                ('raw_attribue', models.CharField(max_length=200)),
                ('raw_condition', models.CharField(max_length=200)),
                ('raw_department', models.CharField(max_length=200)),
                ('raw_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReguData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_num', models.CharField(max_length=200)),
                ('trash_val', models.CharField(max_length=200)),
                ('regu_name', models.CharField(max_length=200)),
                ('regu_paper_num', models.CharField(max_length=200)),
                ('regu_department', models.CharField(max_length=200)),
                ('regu_dates', models.CharField(max_length=200)),
                ('regu_status', models.CharField(max_length=200)),
                ('regu_condition', models.CharField(max_length=200)),
                ('regu_num', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReguNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Link_Page_num', models.CharField(max_length=200)),
            ],
        ),
    ]
