# Generated by Django 2.2.2 on 2019-06-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawdata',
            old_name='raw_attribue',
            new_name='raw_attribute',
        ),
    ]
