# Generated by Django 2.2.2 on 2019-06-26 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parsed_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pa_board',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_boards_pa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pa_board2',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_boards_pa2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='par_board',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_boards_par', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='par_board2',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_boards_par2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pg_board',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_boards_pg', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pg_board2',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_boards_pg2', to=settings.AUTH_USER_MODEL),
        ),
    ]
