# Generated by Django 2.2.2 on 2019-06-26 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parsed_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawdata',
            name='like2_users',
            field=models.ManyToManyField(blank=True, related_name='like2_parsed_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lawdata',
            name='unlike2_users',
            field=models.ManyToManyField(blank=True, related_name='unlike2_parsed_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_parsed_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='unlike_users',
            field=models.ManyToManyField(blank=True, related_name='unlike_parsed_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regudata',
            name='like3_users',
            field=models.ManyToManyField(blank=True, related_name='like3_parsed_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regudata',
            name='unlike3_users',
            field=models.ManyToManyField(blank=True, related_name='unlike3_parsed_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
