# Generated by Django 2.2.2 on 2019-06-25 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0002_auto_20190625_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pa_comment',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pa_comments', to='parsed_data.Pa_Board'),
        ),
        migrations.AlterField(
            model_name='pa_comment2',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pa_comments2', to='parsed_data.Pa_Board2'),
        ),
        migrations.AlterField(
            model_name='par_comment',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='par_comments', to='parsed_data.Par_Board'),
        ),
        migrations.AlterField(
            model_name='par_comment2',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='par_comments2', to='parsed_data.Par_Board2'),
        ),
    ]
