# Generated by Django 2.2.2 on 2019-06-26 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0002_auto_20190626_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg_board',
            name='mboard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pgboard_rn', to='parsed_data.RawData'),
            preserve_default=False,
        ),
    ]
