# Generated by Django 2.2.2 on 2019-06-25 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0003_auto_20190625_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg_comment2',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pd_comments2', to='parsed_data.Pg_Board2'),
        ),
    ]
