# Generated by Django 2.2.2 on 2019-06-26 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0003_pg_board_mboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boardtoboard1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsed_data.Pg_Board')),
                ('rawdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsed_data.RawData')),
            ],
        ),
    ]
