# Generated by Django 2.2.2 on 2019-06-26 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0004_boardtoboard1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pg_board',
            name='mboard',
        ),
    ]
