# Generated by Django 2.2.2 on 2019-06-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0005_remove_pg_board_mboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg_board',
            name='rawdatas',
            field=models.ManyToManyField(through='parsed_data.Boardtoboard1', to='parsed_data.RawData'),
        ),
    ]
