# Generated by Django 2.2.2 on 2019-06-26 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0006_pg_board_rawdatas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pg_board',
            name='rawdatas',
        ),
        migrations.AddField(
            model_name='pg_board',
            name='rawdata',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parsed_data.RawData'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Boardtoboard1',
        ),
    ]
