# Generated by Django 2.2.2 on 2019-06-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='laws',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_num', models.CharField(max_length=200)),
                ('law_name', models.CharField(max_length=200)),
                ('law_attribute', models.CharField(max_length=200)),
                ('law_condition', models.CharField(max_length=200)),
                ('law_department', models.CharField(max_length=200)),
                ('law_status', models.CharField(max_length=200)),
                ('page_num_num', models.CharField(max_length=200)),
            ],
        ),
    ]
